// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tree_bm_compute_cpp
List tree_bm_compute_cpp(int ntip, int total_nodes, IntegerVector roots, NumericVector y, NumericVector s2, NumericVector edge_len_to_child, List children, IntegerVector internal_post, IntegerVector internal_pre, double bm_var);
RcppExport SEXP _ebnm_tree_bm_compute_cpp(SEXP ntipSEXP, SEXP total_nodesSEXP, SEXP rootsSEXP, SEXP ySEXP, SEXP s2SEXP, SEXP edge_len_to_childSEXP, SEXP childrenSEXP, SEXP internal_postSEXP, SEXP internal_preSEXP, SEXP bm_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< int >::type total_nodes(total_nodesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type roots(rootsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_len_to_child(edge_len_to_childSEXP);
    Rcpp::traits::input_parameter< List >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type internal_post(internal_postSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type internal_pre(internal_preSEXP);
    Rcpp::traits::input_parameter< double >::type bm_var(bm_varSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_bm_compute_cpp(ntip, total_nodes, roots, y, s2, edge_len_to_child, children, internal_post, internal_pre, bm_var));
    return rcpp_result_gen;
END_RCPP
}
// tree_ou_compute_cpp
List tree_ou_compute_cpp(int ntip, int total_nodes, IntegerVector roots, NumericVector y, NumericVector s2, NumericVector edge_len_to_child, List children, IntegerVector internal_post, IntegerVector internal_pre, double alpha, double stationary_var);
RcppExport SEXP _ebnm_tree_ou_compute_cpp(SEXP ntipSEXP, SEXP total_nodesSEXP, SEXP rootsSEXP, SEXP ySEXP, SEXP s2SEXP, SEXP edge_len_to_childSEXP, SEXP childrenSEXP, SEXP internal_postSEXP, SEXP internal_preSEXP, SEXP alphaSEXP, SEXP stationary_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< int >::type total_nodes(total_nodesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type roots(rootsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_len_to_child(edge_len_to_childSEXP);
    Rcpp::traits::input_parameter< List >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type internal_post(internal_postSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type internal_pre(internal_preSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type stationary_var(stationary_varSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_ou_compute_cpp(ntip, total_nodes, roots, y, s2, edge_len_to_child, children, internal_post, internal_pre, alpha, stationary_var));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ebnm_tree_bm_compute_cpp", (DL_FUNC) &_ebnm_tree_bm_compute_cpp, 10},
    {"_ebnm_tree_ou_compute_cpp", (DL_FUNC) &_ebnm_tree_ou_compute_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_ebnm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
