# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_bm_compute_cpp <- function(ntip, total_nodes, roots, y, s2, edge_len_to_child, children, internal_post, internal_pre, bm_var) {
    .Call(`_ebnm_tree_bm_compute_cpp`, ntip, total_nodes, roots, y, s2, edge_len_to_child, children, internal_post, internal_pre, bm_var)
}

tree_ou_compute_cpp <- function(ntip, total_nodes, roots, y, s2, edge_len_to_child, children, internal_post, internal_pre, alpha, stationary_var) {
    .Call(`_ebnm_tree_ou_compute_cpp`, ntip, total_nodes, roots, y, s2, edge_len_to_child, children, internal_post, internal_pre, alpha, stationary_var)
}

